language: node_js
node_js:
  - "8.9"

# Cache the node_modules directory
cache:
  directories:
    - node_modules

# Require Docker services
services:
  - docker

env:
  global:
  - Name=pam-apigateway

install:
  - npm install

before_script:
  - npm run lint

script:
#  - npm run test

after_failure:
  - docker ps -a
  - docker logs $NAME

notifications:
  email: false